jekyll:
    image: jekyll/jekyll:pages
    environment:
        - JEKYLL_ENV=development
    command: jekyll serve --config _config.yml,_config_dev.yml --watch --incremental
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
