version: '3'
  
services:
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: sbd_web
    #environment:
    #  - JEKYLL_ENV=development
   # command: jekyll serve --config _config.yml,_config_dev.yml --force_polling --livereload
    command: jekyll build
    ports:
        - 4000:4000
        - 35729:35729
    volumes:
        - .:/srv/jekyll
