# This is a basic workflow to help you get started with Actions

name: Download results

# Controls when the workflow will run
on:
#   schedule:
#     - cron:  '30 5,17 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download remote results file locally
        uses: carlosperate/download-file-action@v1.0.3
        with:
          # URL of the file to download
          file-url: https://drive.google.com/file/d/1hosSQbEFCCUmrknx25cCvyk1r4st4O_i/view?usp=sharing
          # New filename to rename the downloaded file
          file-name: couch_to_soap_box_2021.csv
          # Path to download the file
          location: ./_data

      - name: Commit new results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Adding new version of results"
          branch: "master"
          file_pattern: "_data/couch_to_soap_box_2021.csv"
          repository: .
